spring:
    jpa:
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    datasource:
        url: "jdbc:postgresql://localhost:5432/kabina"
        username: kabina
        password: kaboot
    jackson:
        serialization.FAIL_ON_EMPTY_BEANS: false

org:
    jobrunr:
        background-job-server.enabled: true
        dashboard.enabled: true

logging:
    level:
        org.springframework: ERROR
        no.kabina: DEBUG
    pattern:
        file: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n"
        console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"
    file:
        name: logs/app.log

springdoc:
    api-docs:
        path: /api-docs
kaboot:
    consts:
        max-non-lcm: 200
        max-pool4: 300
        max-pool3: 600
        max-stand: 50
    scheduler:
        online: true
        at-time-lag: 3
    solver:
        cmd: "glpsol -m glpk.mod"
        input: "glpk.mod"
        output: "out.txt"
    extern-pool:
        cmd: "findpool"
        input-file: "pool-in.csv"
        output-file: "pool-out.csv"
        threads: 8