spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/kabina"
    username: kabina
    password: kaboot

kaboot:
  consts:
    max-non-lcm: 200
    max-pool4: 300
    max-pool3: 600
    max-stand: 50
    scheduler:
      online: true
    extern-pool:
      cmd: "findpool.exe"
      input-file: "pool-in.csv"
      output-file: "pools.csv"